### ISSUE TITLE
Adding gdb to the docker image

### ISSUE THREAD

**Issue by ghost** [little-big-h/DPS-Docker-Image#1]
Hey, 
I was wondering if it would be possible to add `gdb` to the docker image, would be fairly helpful to debug when the program crashes!
If it is not possible is there any way I can get a docker image with `gdb` in it as well?

**Comment by little-big-h** [comment]
Why don't you just fork the repository? You could also make a derived docker image (see https://docs.docker.com/build/building/multi-stage/).

**Comment by ghost** [comment]
Hey, I forked the repo, added and  committed the packages I need to the Dockerfile but I'm not sure how to get actions to build and push the docker image, any advice?
